todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'todolist/', include(('todolist.urls', 'todolist'), namespace='todolist')),
]

todolist/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    path(r'^delete/<list_id>', views.delete, name='delete'),
    path(r'^cross_off/<list_id>', views.cross_off, name='cross_off'),
    path(r'^uncross/<list_id>', views.uncross, name='uncross'),
    path(r'^edit/<list_id>', views.edit, name='edit'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


class ListNew(models.Model):
    item = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.item + '|' + str(self.completed)

todolist/forms.py
from django import forms
from .models import ListNew


class ListForm(forms.ModelForm):
    class Meta:
        model = ListNew
        fields = ["item", "completed", "owner"]

todolist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import ListForm
from .models import ListNew
from django.contrib import messages


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/todolist/index')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.error(request, ('Invalid login details given!'))
            # return HttpResponse("Invalid login details given")
            return HttpResponseRedirect(request.path_info)

    else:
        return render(request, 'todolist/login.html', {})


@login_required
def logout(request):
    print("logout")
    auth_logout(request)
    return HttpResponseRedirect('/todolist/login')


@login_required(login_url="/todolist/login/")
def index(request):
    user = request.user
    if request.method == 'POST':
        post_values = request.POST.copy()
        post_values['owner'] = user.id
        form = ListForm(post_values or None)

        if form.is_valid():
            form.save()
            all_items = ListNew.objects.all()
            messages.success(request, ('Item has been added to list!'))
            # return render(request, 'todolist/index.html', {'all_items': all_items})
            return HttpResponseRedirect(request.path_info)
    else:
        all_items = ListNew.objects.filter(owner=user)
        return render(request, 'todolist/index.html', {'all_items': all_items})


@login_required(login_url="/todolist/login/")
def delete(request, list_id):
    item = ListNew.objects.get(pk=list_id)
    item.delete()
    messages.success(request, ('Item has been deleted!'))
    return redirect('/todolist/index')


@login_required(login_url="/todolist/login/")
def edit(request, list_id):
    if request.method == 'POST':
        item = ListNew.objects.get(pk=list_id)

        user = request.user
        post_values = request.POST.copy()

        post_values['owner'] = user.id

        form = ListForm(post_values or None, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, ('Item has been edited!'))
        return HttpResponseRedirect('/todolist/index')

    else:
        item = ListNew.objects.get(pk=list_id)
        return render(request, 'todolist/edit.html', {"item": item})


@login_required(login_url="/todolist/login/")
def cross_off(request, list_id):
    item = ListNew.objects.get(pk=list_id)
    item.completed = True
    item.save()
    return redirect('/todolist/index')


@login_required(login_url="/todolist/login/")
def uncross(request, list_id):
    item = ListNew.objects.get(pk=list_id)
    item.completed = False
    item.save()
    return redirect('/todolist/index')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            _user_name = form.cleaned_data.get('username')
            _raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=_user_name, password=_raw_password)
            auth_login(request, user)
        return redirect('/todolist/login')
    else:
        form = UserCreationForm()
    return render(request, 'todolist/signup.html', {'form': form})




todolist/templates/todolist/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>To-do App</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'todolist:signup' %}">Sign Up</a>
  <a class="navbar-brand" href="{% url 'todolist:login' %}">Login</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small>
                            <sup>x</sup>
                        </small>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todolist/templates/todolist/edit.html
{% extends 'todolist/user_base.html' %}

{% block content %}
    {% if item %}
            <form class="form-inline my-2 my-lg-0", method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="{{ item.item }}" value="{{ item.item }}" aria-label="Search" name="item">
                <input type="hidden" value="{{ item.completed }}" name="completed">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" style="margin-right: .5rem!important;">Edit Item</button>
                <a href="{% url 'todolist:index' %}">Cancel</a>
            </form>

    {% endif %}
{% endblock %}

todolist/templates/todolist/index.html
{% extends 'todolist/user_base.html' %}

{% block content %}

{% if all_items %}
<table class="table table-bordered">
    {% for things in all_items %}
            {% if things.completed %}
                <tr>
                    <td class="striker"><a href="{% url 'todolist:edit' things.id %}">{{ things.item }}</a></td>
                    <td><center><a href="{% url 'todolist:uncross' things.id %}">Uncross</a></center></td>
                    <td><center><a href="{% url 'todolist:delete' things.id %}">Delete</a></center></td>
                </tr>
            {% else %}
                <tr>
                    <td><a href="{% url 'todolist:edit' things.id %}">{{ things.item }}</a></td>
                    <td><center><a href="{% url 'todolist:cross_off' things.id %}">Cross Off</a></center></td>
                    <td><center><a href="{% url 'todolist:delete' things.id %}">Delete</a></center></td>
                </tr>
            {% endif %}


    {% endfor %}
</table>
{% endif %}
{% endblock %}

todolist/templates/todolist/login.html
{% extends 'todolist/base.html' %}
{% block content %}
  <div>
    <div class="tabcontent" style="display:block;">
        <br>
      <h3>Login here :</h3>
        <form method="post" action="{% url 'todolist:login' %}">
              {% csrf_token %}
              <label for="username">Username:</label>
              <input type="text" name="username" placeholder="Username"><br>
              <label for="password">Password:</label>
              <input type="password" name="password" placeholder="Password"><br>
              <input type="submit" name="" value="Login">
        </form>
</div>
  </div>
{% endblock %}

todolist/templates/todolist/signup.html
{% extends 'todolist/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

todolist/templates/todolist/user_base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_css.css' %}">
    <title>To-do App</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <div>

            <form class="form-inline my-2 my-lg-0" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Add Item" aria-label="Search" name="item">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add To List</button>
            </form>

        </div>
        <form class="form-inline my-2 my-lg-0" action="{% url 'todolist:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-secondary my-2 my-sm-0 logout-btn" name="logout" id="logout"  value="Log Out">Log Out</button>
        </form>

</nav>
    <div class="container">
        <br>
        <br>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small>
                            <sup>x</sup>
                        </small>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>